[tool.isort]
profile = "black"
src_paths = ["src", "api_demo_apicall", "api_faq_db", "api_model"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rP"
testpaths = ["tests"]
python_files = ["*.py"]
markers = [
    "slow: mark test as slow", 
    "fast: mark test as fast", 
    "extended: for detailed test run"
]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ResourceWarning"
]
