[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rP"
testpaths = ["tests"]
python_files = ["*.py"]
markers = [
    "slow: mark test as slow", 
    "fast: mark test as fast", 
    "extended: for detailed test run"
]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ResourceWarning"
]
env_files = ["tests/configs/env.vars"]
