"""empty message

Revision ID: 028a8fe5e360
Revises: d8fd89943836
Create Date: 2022-12-22 14:31:56.913739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "028a8fe5e360"
down_revision = "d8fd89943836"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faqmatches", sa.Column("faq_questions", sa.ARRAY(sa.String()), nullable=True)
    )
    op.execute(
        "UPDATE inbounds SET inbound_secret_key = 'abc_123' WHERE inbound_secret_key is NULL"
    )
    op.execute(
        "UPDATE faqmatches SET faq_questions = ARRAY ['Dummy question 1','Dummy question 2','Dummy question 3', 'Dummy question 4','Dummy question 5'] WHERE faq_questions is NULL"
    )
    op.alter_column(
        "inbounds", "inbound_secret_key", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inbounds", "inbound_secret_key", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("faqmatches", "faq_questions")
    # ### end Alembic commands ###
