"""empty message

Revision ID: 1e941a9520db
Revises: 0bf0832995a6
Create Date: 2023-03-02 16:42:40.668061

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e941a9520db"
down_revision = "0bf0832995a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    language_context_table = op.create_table(
        "contextualization",
        sa.Column("contextualization_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.String(), nullable=False),
        sa.Column("config_added_utc", sa.DateTime(), nullable=False),
        sa.Column("config_updated_utc", sa.DateTime(), nullable=True),
        sa.Column(
            "custom_wvs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "pairwise_triplewise_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "tag_guiding_typos", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("contextualization_id"),
    )
    op.bulk_insert(
        language_context_table,
        [
            {
                "version_id": "f56ce629f5c4e81c",
                "custom_wvs": {
                    "coronavirus": {"virus": 0.8, "pandemic": 0.2},
                    "covid": {"virus": 0.8, "pandemic": 0.2},
                },
                "pairwise_triplewise_entities": {
                    "(second, dose)": "second_dose",
                    "(side, effect)": "side_effects",
                },
                "tag_guiding_typos": ["immunity", "vaccination"],
                "config_added_utc": datetime.now(),
                "active": True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contextualization")
    # ### end Alembic commands ###
