"""empty message

Revision ID: 5a4abb131d46
Revises: 0bf0832995a6
Create Date: 2023-03-01 16:44:38.078091

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a4abb131d46"
down_revision = "0bf0832995a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appconfig",
        sa.Column("app_config_id", sa.Integer(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("app_config_id"),
    )
    op.create_table(
        "contextualization",
        sa.Column("contextualization_id", sa.Integer(), nullable=False),
        sa.Column(
            "custom_wvs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "pairwise_triplewise_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "tag_guiding_typos", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("contextualization_id"),
    )
    op.create_table(
        "config",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("config_added_utc", sa.DateTime(), nullable=False),
        sa.Column("config_updated_utc", sa.DateTime(), nullable=True),
        sa.Column("app_config_id", sa.Integer(), nullable=True),
        sa.Column("contextualization_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_config_id"],
            ["appconfig.app_config_id"],
        ),
        sa.ForeignKeyConstraint(
            ["contextualization_id"],
            ["contextualization.contextualization_id"],
        ),
        sa.PrimaryKeyConstraint("config_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config")
    op.drop_table("contextualization")
    op.drop_table("appconfig")
    # ### end Alembic commands ###
