"""empty message

Revision ID: c86ead81ee4f
Revises: 028a8fe5e360
Create Date: 2022-12-28 10:11:59.361404

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c86ead81ee4f"
down_revision = "028a8fe5e360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ud_inbounds")
    op.alter_column(
        "faqmatches",
        "faq_questions",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.execute(
        "UPDATE faqmatches SET faq_questions = ARRAY ['Dummy question 1','Dummy question 2','Dummy question 3', 'Dummy question 4','Dummy question 5']"
    )
    op.alter_column("faqmatches", "faq_questions", nullable=False)
    op.drop_column("faqmatches", "test_migration")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faqmatches",
        sa.Column("test_migration", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "faqmatches",
        "faq_questions",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.create_table(
        "ud_inbounds",
        sa.Column("inbound_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("inbound_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "inbound_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "inbound_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "urgency_score",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "returned_content",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "returned_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "returned_feedback",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "feedback_secret_key", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("inbound_id", name="ud_inbounds_pkey"),
    )
    # ### end Alembic commands ###
