apiVersion: 1

datasources:
  - name: MomConnect AAQ Prometheus
    type: prometheus
    uid: QyNyap_7k
    editable: true
    is_default: true
    access: proxy
    url: http://host.docker.internal:9090
