global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'mc-core'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9902']
  - job_name: 'uptime-mc-core'
    scrape_interval: 300s
    static_configs:
    - targets: ['host.docker.internal:9705']
