version: '2'
services:
    core:
        image: 678681925278.dkr.ecr.af-south-1.amazonaws.com/aaq_solution/praekelt_mc_core:v1.0.0
        cpu_shares: 1200
        mem_limit: 13048576000
        environment:
          # app secrets
          - INBOUND_CHECK_TOKEN=${INBOUND_CHECK_TOKEN}
          - ENABLE_FAQ_REFRESH_CRON=${ENABLE_FAQ_REFRESH_CRON}
          - PROMETHEUS_MULTIPROC_DIR=${PROMETHEUS_MULTIPROC_DIR}
          # database secrets
          - PG_ENDPOINT=${PG_ENDPOINT}
          - PG_PORT=${PG_PORT}
          - PG_USERNAME=${PG_USERNAME}
          - PG_PASSWORD=${PG_PASSWORD}
          - PG_DATABASE=${PG_DATABASE}
          # sentry config
          - SENTRY_DSN=${SENTRY_DSN}
          - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
          - SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE}
        ports:
            - "${PORT}:${PORT}"
        logging:
          driver: awslogs
          options:
            awslogs-group: aaq_solution
            awslogs-region: af-south-1
            awslogs-stream-prefix: ${PROJECT_NAME}
        volumes:
            - /home/ec2-user/data/GoogleNews-vectors-negative300-prenorm.bin:/usr/src/data/pretrained_wv_models/GoogleNews-vectors-negative300-prenorm.bin
        