PG_PORT: 5432
PG_DATABASE: aaq-template-db-test
PG_USERNAME: flask_test
MODEL_PORT: 9902
MODEL_PROTOCOL: http
THRESHOLD_CRITERIA: 0.5
TRUE_FAQ_COL: "FAQ Name"
QUERY_COL: "Question"
VALIDATION_DATA_PREFIX: validation_aaq/validation_khumo_labelled_phase1and2_with_dem_context_clean.csv
VALIDATION_FAQ_PREFIX: mc_validation/praekelt_mc_faqs_trimester_tag.csv
MATCHING_MODEL: simple_fasttext_with_faq
CONTEXT_ACTIVE: True
# MATCHING_MODEL: simple_fasttext_with_faq google_news_pretrained # commented out to use matching_model from app config
