PG_PORT: 5432
PG_DATABASE: aaq-template-db-test
PG_USERNAME: flask_test
MODEL_PORT: 9902
MODEL_PROTOCOL: http
THRESHOLD_CRITERIA: 0.5
TRUE_FAQ_COL: "faq_name"
QUERY_COL: "question"
FILTER_CONDITIONS:
  correct_answer: "Yes"
VALIDATION_DATA_PREFIX: experiment/data/mc/mc_openai_validation.csv
VALIDATION_FAQ_PREFIX: experiment/data/mc/mc_openai_faqs.csv
# MATCHING_MODEL: simple_fasttext_with_faq # commented out to use matching_model from app config
