PG_PORT: 5432
PG_DATABASE: aaq-template-db-test
PG_USERNAME: flask_test
MODEL_PORT: 9902
MODEL_PROTOCOL: http
THRESHOLD_CRITERIA: 0.5
FAQ_COLUMN_MAP:
  faq_title: faq_name
  faq_tags: faq_tags
  faq_content_to_send: faq_content_to_send
  faq_contexts: faq_contexts
TRUE_FAQ_FILTER_CONDITIONS:  
  # Column values to filter validation rows with FAQs that answered user questions
  correct_answer: "Yes"
  # "is_concern_addressed": "Yes"
QUERY_COL: "question"
VALIDATION_DATA_PREFIX: experiment/data/mc/mc_openai_validation.csv
VALIDATION_FAQ_PREFIX: experiment/data/mc/mc_openai_faqs.csv
MATCHING_MODEL: simple_fasttext_with_faq
CONTEXT_ACTIVE: False
# MATCHING_MODEL: simple_fasttext_with_faq google_news_pretrained # commented out to use matching_model from app config
