PG_PORT: 5432
PG_DATABASE: aaq-template-db-test
PG_USERNAME: flask_test
MODEL_PORT: 9902
MODEL_PROTOCOL: http
THRESHOLD_CRITERIA: 0.5
TRUE_FAQ_COL: "FAQ Name"
QUERY_COL: "Question"
VALIDATION_DATA_PREFIX: # S3 key to Test data
VALIDATION_FAQ_PREFIX: # S3 key to FAQ data
matching_model: google_news_pretrained
