preprocessing:
  min_dashed_words_to_parse_text_from_url: 4
  reincluded_stop_words:
    - how
    - what
    - who
    - in
    - where
    - can
faq_match:
  N_TOP_MATCHES_PER_PAGE: 5
matching_model:
  google_news_pretrained # google_news_pretrained # simple_fasttext_with_faq
model_params:
  # Params for model to be used. Each key should be a key in `data_sources.yml`
  google_news_pretrained:
    tag_scoring_method: cs_nearest_k_percent_average
    tag_scoring_kwargs:
      k: 10
      floor: 1
    score_reduction_method: simple_mean
    score_reduction_kwargs:
    weighting_method: add_weight
    weighting_kwargs:
      N: 5
  simple_fasttext_with_faq:
    tag_scoring_method: cs_nearest_k_percent_average
    tag_scoring_kwargs:
      k: 10
      floor: 1
    score_reduction_method: simple_mean
    score_reduction_kwargs:
    weighting_method: add_weight
    weighting_kwargs:
      N: 5
contextualization:
  active: True 
  context_list: ["design", "code", "test", "deploy","maintain"]
