preprocessing:
  min_dashed_words_to_parse_text_from_url: 4
  scoring_function_args:
    k: 10
    floor: 1
  reincluded_stop_words:
    - how
    - what
    - who
    - in
    - where
    - can
faq_match:
  n_top_matches_per_page: 10
score_reduction:
  REDUCTION_FUNCTION: simple_mean
  REDUCTION_FUNCTION_ARGS:
    N: 5
