name: Docker Make and Push Release Image and Deploy to staging
on:
  # release:
  #   # Only use the types keyword to narrow down the activity types that will trigger your workflow.
  #   types: [published]
   push:
    branches:
      - ecs_deployment

jobs:
  DockerMakeAndPushRelease:
    name: Build docker image and push to ECR
    runs-on: ubuntu-latest
    environment: staging
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
      ecr-image-path: ${{ steps.update-ecr.outputs.EcrImagePath }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Docker image
        run: |
          cp ./requirements.txt ./core_model/requirements.txt
          docker build --rm \
            --build-arg NAME=${{ github.event.repository.name }} \
            --build-arg PORT=9902 \
            --build-arg TOKEN_MACHINE_USER=${{ secrets.TOKEN_MACHINE_USER }} \
            -t $IMAGE_NAME \
            ./core_model
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker tag and push image to ECR 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        id: update-ecr
        run: |
          docker image tag ${IMAGE_NAME} $ECR_REGISTRY/aaq_solution/${IMAGE_NAME}
          echo "::set-output name=EcrImagePath::$ECR_REGISTRY/aaq_solution/${IMAGE_NAME}"

  DeployStagingECSCluster:
    name: Deploy ECS cluster
    needs: [DockerMakeAndPushRelease, RefreshStagingDatabase]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install the ECS CLI
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load project config variables
        id: get-project-config
        uses: ./.github/actions/setup-environment
        with:
          environment-config-file: "project_config.cfg"

      - name: Pull down ECS service
        env:
          IMAGE_NAME: ${{ needs.DockerMakeAndPushRelease.outputs.ecr-image-path }}
          PROJECT_NAME: ${{ steps.get-project-config.outputs.PROJECT_NAME }}
          PROJECT_SHORT_NAME: ${{ steps.get-project-config.outputs.PROJECT_SHORT_NAME }}
        run: |
          ecs-cli compose \
          -f docker-compose/docker-compose-stg.yml \
          --project-name ${PROJECT_NAME} \
          --cluster-config ${PROJECT_NAME}-config \
          --cluster ${PROJECT_SHORT_NAME}-cluster \
          service down --timeout 10

      - name: Deploy using ECS CLI
        env:
          IMAGE_NAME: ${{ needs.DockerMakeAndPushRelease.outputs.ecr-image-path }}
          PROJECT_NAME: ${{ steps.get-project-config.outputs.PROJECT_NAME }}
          PROJECT_SHORT_NAME: ${{ steps.get-project-config.outputs.PROJECT_SHORT_NAME }}
          PORT: 9902
          AWS_REGION: ${{ secrets.AWS_REGION }}

          # app secrets
          INBOUND_CHECK_TOKEN: ${{ secrets.GA_INBOUND_CHECK_TOKEN }}
          ENABLE_FAQ_REFRESH_CRON: ${{ secrets.GA_ENABLE_FAQ_REFRESH_CRON}}
          PROMETHEUS_MULTIPROC_DIR: ${{ secrets.GA_PROMETHEUS_MULTIPROC_DIR }}
          # database secrets
          PG_ENDPOINT: ${{ secrets.GA_PG_ENDPOINT }}
          PG_PORT: 5432
          PG_USERNAME: "flask"
          PG_PASSWORD: ${{ secrets.GA_PG_PASSWORD }}
          PG_DATABASE: ${{ steps.get-project-config.outputs.PROJECT_SHORT_NAME }}
          # sentry config
          SENTRY_DSN: ${{ secrets.GA_SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.GA_SENTRY_ENVIRONMENT }}
          SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.GA_SENTRY_TRACES_SAMPLE_RATE }}

        run: |
          ecs-cli configure \
          --cluster ${PROJECT_SHORT_NAME}-cluster \
          --default-launch-type EC2 \
          --region ${AWS_REGION} \
          --config-name ${PROJECT_NAME}-config

          ecs-cli compose \
          -f docker-compose/docker-compose-stg.yml \
          --project-name ${PROJECT_NAME} \
          --cluster-config ${PROJECT_NAME}-config \
          --task-role-arn arn:aws:iam::678681925278:role/${PROJECT_SHORT_NAME}-task-role \
          service up \
          --create-log-groups \
          --deployment-min-healthy-percent 0 
