name: Test and Validation
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'


jobs:
  ValidateModels:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get AWS secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |  # Replace ARNs with your own
            CORE, arn:aws:secretsmanager:af-south-1:678681925278:secret:aaq-template-core-secrets-F64A4Z
            GLOBAL, arn:aws:secretsmanager:af-south-1:678681925278:secret:aaq-template-global-secrets-HEQCSO
          parse-json-secrets: true

      - name: Install Python libraries
        run: |
          pip install -r requirements.txt
          pip install -r requirements_github_actions.txt
          nltkdownload=`cat <<EOF
          import nltk
          nltk.download('stopwords')
          nltk.download('punkt')
          EOF`
          python -c "$nltkdownload"

      - name: Run Unit Tests
        env:
          PG_ENDPOINT: ${{env.GLOBAL_PG_ENDPOINT}}
          PG_PASSWORD: ${{env.GLOBAL_PG_PASSWORD}}
          INBOUND_CHECK_TOKEN: ${{env.CORE_INBOUND_CHECK_TOKEN}}
          WORD2VEC_BINARY_BUCKET: ${{env.CORE_WORD2VEC_BINARY_BUCKET}}
          PROMETHEUS_MULTIPROC_DIR: /tmp
        run: |
          coverage run -m pytest tests -m "not extended" --durations=0
          coverage lcov --include="core_model/*"

      - name: Run Validation Tests
        env:
          VALIDATION_BUCKET: ${{env.CORE_VALIDATION_BUCKET}}
          VALIDATION_DATA_PREFIX: ${{env.CORE_VALIDATION_DATA_PREFIX}}
          VALIDATION_FAQ_PREFIX: ${{env.CORE_VALIDATION_FAQ_PREFIX}}
          REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
          PROMETHEUS_MULTIPROC_DIR: /tmp
          PG_ENDPOINT: ${{env.GLOBAL_PG_ENDPOINT}}
          PG_PASSWORD: ${{env.GLOBAL_PG_PASSWORD}}
          INBOUND_CHECK_TOKEN: ${{env.CORE_INBOUND_CHECK_TOKEN}}
          WORD2VEC_BINARY_BUCKET: ${{env.CORE_WORD2VEC_BINARY_BUCKET}}
        if: "${{ (env.CORE_VALIDATION_BUCKET != '') && (env.CORE_VALIDATION_DATA_PREFIX != '') && (env.CORE_VALIDATION_FAQ_PREFIX != '')}}"
        run: |
          # for testing
          python -m pytest validation

      - name: Coveralls Test Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
